language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 sview
- flake8 tests
script: py.test tests
deploy:
  provider: pypi
  user: dusktreader
  password:
    secure: DQLLbw7POi4T7V3inT4fAZ+Z59/Mb5zm11Qkx1QX1iZk7Wobi6kVp1/JEoYdWwAQo4vTW0j2zJJK3TN8+mMATOqBPGCiWozZe1V2gQhIx5zuAj+z7jLnsl5TvFIFcQeTCoLY5ko4poHK5Cth4M/IbX/0YIyv2ks+NSML2dY95EBwXSqcuKbE4KFThVEDdwevQAj12/9wP4y69MPNfn/kZZWWQiAbsaAw6vMhErg1xdi3q9I3aO+cwNcD/jmHzA4alEuYN8P80fOp5Vryqs6Wxk/pVvZOBWxrkhOlZessEvVDLQZzGm6JmPa1yalJUicu38Y0K1Eogm7db/WtkWsgYXpTTpctHC6Yylkd6Dci0ruD72FjkH3BIwPe1bJh2kBnfpkH9t5249aR6RMACgEqRE5ohxtsAftxwXIu35omUjcjGsj0js23G9Ec1gYgfyFV0L3vbQgn30VuSKJq1Zmul2bUWi+cZ+zybQqiTsjTxOnlDLAjpBUaGQVwZaahToN+BQ+rFmtetoLa9SbvldSoPbyYnbRu5Hr0jEsa+QuMx6WZHA7iUD0N75XEMYQ8uUPOjWakllcbVmpOQYMw7urG1OaXR5mhCryTGguX6+uSItSiVaoJJfkUJyYxZzw9DyEGTutaVNNLeZDUMRq45TrE/xntl0SQqFjtyC1NjB6gDfQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dusktreader/sphinx-view
